// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/index.tsx';
import * as $$0 from './islands/Hero.tsx';
import * as $$1 from './islands/HeroText.tsx';
import * as $$2 from './islands/Project.tsx';
import * as $$3 from './islands/ProjectList.tsx';
import * as $$4 from './islands/SiteHead.tsx';

const manifest = {
    routes: {
        './routes/index.tsx': $0,
    },
    islands: {
        './islands/Hero.tsx': $$0,
        './islands/HeroText.tsx': $$1,
        './islands/Project.tsx': $$2,
        './islands/ProjectList.tsx': $$3,
        './islands/SiteHead.tsx': $$4,
    },
    baseUrl: import.meta.url,
};

export default manifest;
